### PR TITLE
use base class parseTime

### PR DESCRIPTION
**Pull request by VladVega**
Use parseTime instead of the same logic in the adapter. https://github.com/juttle/juttle-postgres-adapter/issues/13

@rlgomes @davidvgalbraith @dmehra

### CODE REVIEW

**Comment by dmehra** [comment]
Does this fix https://github.com/juttle/juttle-postgres-adapter/issues/10 or is this a separate good thing to do?

**Comment by VladVega** [comment]
It should NOT fix that issue. I had the same code previously - just didn't realize i could reuse the base class in this case.

**Comment by davidvgalbraith** [comment]
+1

**Comment by dmajda** [comment]
@VladVega I noticed that `parseTime` doesn’t delete the specified time field from the points, which causes a change in behavior of SQL adapters. Is that intentional?

**Pull request merged**
