### PR TITLE
change: jshint and jscs to eslint and add coverage

### PR DESCRIPTION
**Pull request by VladVega**
change: jshint and jscs to eslint and add coverage

https://github.com/juttle/juttle-sql-adapter-common/issues/22 and https://github.com/juttle/juttle-sql-adapter-common/issues/28

### CODE REVIEW

**Comment by VladVega** [comment]
@rlgomes @demmer @davidvgalbraith

**Comment by VladVega** [comment]
Check out what I did for npm scripts. It's kind of crazy but I like it.

**Comment by davidvgalbraith** [comment]
+1

**Comment by dmehra** [comment]
Did the coverage report pinpoint any areas where we should improve tests?

**Pull request merged**
