### PR TITLE
wrap read in a promise

### PR DESCRIPTION
**Pull request by VladVega**
Wrap read function logic in a `Promise.try`.

### CODE REVIEW

**Comment by VladVega** [comment]
@davidvgalbraith

**Comment by davidvgalbraith** [comment]
Looking good! Can you even move all your `formatPoints`es into a `.then` on this promise?

**Comment by VladVega** [comment]
Thanks!

Sadly no because the aggregate batch queries use formatPoints a bit differently.

**Comment by davidvgalbraith** [comment]
How so?

**Comment by VladVega** [comment]
The batching must call format one batch at a time: https://github.com/juttle/juttle-sql-adapter-common/blob/wrap-read-in-promise/lib/read.js#L255

**Comment by VladVega** [comment]
I have it in mind to take
```
if (this.addPointFormatting) {
            this.addPointFormatting(points, this.aggregation_targets);
        }

        if (this.empty_aggregate) {
            points = this.handleNullAggregates(points);
        }
```

out of formatPoints then I can do what you're saying. I'll get there eventually.

**Comment by davidvgalbraith** [comment]
Still don't get the `formatPoints` thing but it sounds like you're on top of it. +1 on this

**Pull request merged**
